<?php

namespace Database\Seeders;

use App\Models\CompanyBranding;
use Illuminate\Database\Seeder;

class CompanyBrandingSeeder extends Seeder
{
    public function run(): void
    {
        CompanyBranding::create([
            'company_name' => 'NyoUniverse',
            'address' => 'Jl. Contoh No. 123, Jakarta',
            'phone' => '+62 21 1234567',
            'email' => 'info@nyouniverse.local',
            'website' => 'https://nyouniverse.local',
            'department_name' => 'Quality Assurance',
            'report_footer' => 'This document is generated by NyoUniverse. For internal use only.',
        ]);
    }
}
